# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: conf.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nconf.proto\"Z\n\x04\x63ord\x12\x0c\n\x04num0\x18\x01 \x01(\x02\x12\x0c\n\x04num1\x18\x02 \x01(\x02\x12\x0c\n\x04num2\x18\x03 \x01(\x02\x12\x0c\n\x04num3\x18\x04 \x01(\x02\x12\x0c\n\x04num4\x18\x05 \x01(\x02\x12\x0c\n\x04num5\x18\x06 \x01(\x02\"=\n\x06Person\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\x9a\x01\n\x07\x61llShip\x12\x1e\n\talignment\x18\x01 \x01(\x0e\x32\x0b.eAlignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\x04\x63las\x18\x03 \x01(\x0e\x32\x07.eClass\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x10\n\x08\x63rewSize\x18\x05 \x01(\x03\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12\x19\n\x08officers\x18\x07 \x03(\x0b\x32\x07.Person*]\n\x06\x65\x43lass\x12\x0c\n\x08\x43orvette\x10\x00\x12\x0b\n\x07\x46rigate\x10\x01\x12\x0b\n\x07\x43ruiser\x10\x02\x12\r\n\tDestroyer\x10\x03\x12\x0b\n\x07\x43\x61rrier\x10\x04\x12\x0f\n\x0b\x44readnought\x10\x05*!\n\neAlignment\x12\x08\n\x04\x41lly\x10\x00\x12\t\n\x05\x45nemy\x10\x01\x32/\n\rgenShipServer\x12\x1e\n\x07getShip\x12\x05.cord\x1a\x08.allShip\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conf_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ECLASS']._serialized_start=326
  _globals['_ECLASS']._serialized_end=419
  _globals['_EALIGNMENT']._serialized_start=421
  _globals['_EALIGNMENT']._serialized_end=454
  _globals['_CORD']._serialized_start=14
  _globals['_CORD']._serialized_end=104
  _globals['_PERSON']._serialized_start=106
  _globals['_PERSON']._serialized_end=167
  _globals['_ALLSHIP']._serialized_start=170
  _globals['_ALLSHIP']._serialized_end=324
  _globals['_GENSHIPSERVER']._serialized_start=456
  _globals['_GENSHIPSERVER']._serialized_end=503
# @@protoc_insertion_point(module_scope)
