# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import conf_pb2 as conf__pb2


class genShipServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getShip = channel.unary_stream(
                '/genShipServer/getShip',
                request_serializer=conf__pb2.cord.SerializeToString,
                response_deserializer=conf__pb2.allShip.FromString,
                )


class genShipServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getShip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_genShipServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getShip': grpc.unary_stream_rpc_method_handler(
                    servicer.getShip,
                    request_deserializer=conf__pb2.cord.FromString,
                    response_serializer=conf__pb2.allShip.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genShipServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class genShipServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getShip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/genShipServer/getShip',
            conf__pb2.cord.SerializeToString,
            conf__pb2.allShip.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
